### ISSUE TITLE
Remaining Explainations

### ISSUE THREAD

**Issue by doctormo** [IQSS/gentb-site#52]
These fields need a description:
-      sptype?
-      inttype?  
-      IS6110?
-      RFLPfamily?
-      spfamily_parentstrain?
-      PGG?
-      spoligo_octal?  

Also can you explain what h34rv is, it's a code of some kind?
- hqr
- hqrref
- fq
- aavar

**Comment by mahafarhat** [comment]
So in general all of the fields below describe the results of genotyping experiments that "type" the MTB bacteria:

sptype: is "spoligotype" its a method of genotyping TB, this will always be an integer type (discard the letter data these were place holders)
inttype: is a method of coding the "RFLP" type it's a complementary method of genotyping TB. Its also an integer (please discard the letter data they were just place holders)
IS6110: is a different way of representing RFLP type it's also an integer 
RFLPfamily: can be integer only (discard 0)
spfamily_parentstrain: should be text (varchar)
SNP_cluster_group and will always start with SCG and then be followed by a number and possibly a letter
SNP_set will only consist of G,C, T, A (nucleotide sequence) and will only be 9 characters long
SNP_cluster_group2 will always start with SCG but otherwise best characterized by varchar.
PGG: principle genetic group also a number/letter classification of genotype
spoligooctal: is an octal number to represent the spoligotype

H37rv is a reference TBgenome, SNPs and mutations are usually called relative to this reference
hqr is the number of sequencing reads that call the mutation
hqrref is the number of sequencing reads that call the reference sequence
(hqr+hqrref is always equal to the depth)
fq is a measure of sequence quality
aavar is the variant aminoacid it's placed there to take into account the effect of multiple mutations in the same codon

**Comment by mahafarhat** [comment]
I will close this for now. feel free to reopen if needed
